sude: required
services:
  - docker

before_install:
  - docker build --file Dockerfile.dev --tag romka04/docker-react . 

script:
  - docker run romka04/docker-react npm run test -- --coverage --watchAll=false