sude: required
services:
  - docker

before_install:
  - docker build --file Dockerfile.dev --tag romka04/docker-react . 

script:
  - docker run romka04/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAV233ZI7IDAEQXXFX
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-401302177744"
  on:
    branch: main